// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLo3X4yUrEhoeN8N2_N09W7RLL8dE9E2Q',
    appId: '1:360701359285:web:21d08e289544bfe32e3afc',
    messagingSenderId: '360701359285',
    projectId: 'teamflow-34bed',
    authDomain: 'teamflow-34bed.firebaseapp.com',
    storageBucket: 'teamflow-34bed.firebasestorage.app',
    measurementId: 'G-FT7R7176GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRAWeWMDyqieAStOVM7WLyHZ04YFMSfYQ',
    appId: '1:360701359285:android:b7ef8b56c07313722e3afc',
    messagingSenderId: '360701359285',
    projectId: 'teamflow-34bed',
    storageBucket: 'teamflow-34bed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBvxdQmKAa4adJUIb22iBZ2ZzENrrsAA',
    appId: '1:360701359285:ios:649b6ac4d6161ec02e3afc',
    messagingSenderId: '360701359285',
    projectId: 'teamflow-34bed',
    storageBucket: 'teamflow-34bed.firebasestorage.app',
    iosBundleId: 'com.example.teamFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMBvxdQmKAa4adJUIb22iBZ2ZzENrrsAA',
    appId: '1:360701359285:ios:649b6ac4d6161ec02e3afc',
    messagingSenderId: '360701359285',
    projectId: 'teamflow-34bed',
    storageBucket: 'teamflow-34bed.firebasestorage.app',
    iosBundleId: 'com.example.teamFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLo3X4yUrEhoeN8N2_N09W7RLL8dE9E2Q',
    appId: '1:360701359285:web:6b2c1a8d37bdb1a22e3afc',
    messagingSenderId: '360701359285',
    projectId: 'teamflow-34bed',
    authDomain: 'teamflow-34bed.firebaseapp.com',
    storageBucket: 'teamflow-34bed.firebasestorage.app',
    measurementId: 'G-7NP686Q4HS',
  );
}
